// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AlgoliaSearchBox: typeof import('./components/AlgoliaSearchBox.vue')['default']
    ArrowLeft: typeof import('./components/icons/ArrowLeft.vue')['default']
    ArrowRight: typeof import('./components/icons/ArrowRight.vue')['default']
    BuySellAds: typeof import('./components/BuySellAds.vue')['default']
    DarkModeSwitch: typeof import('./components/navbar/DarkModeSwitch.vue')['default']
    EditLink: typeof import('./components/EditLink.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    HomeFeatures: typeof import('./components/HomeFeatures.vue')['default']
    HomeFooter: typeof import('./components/HomeFooter.vue')['default']
    HomeHero: typeof import('./components/HomeHero.vue')['default']
    LastUpdated: typeof import('./components/LastUpdated.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NavBarTitle: typeof import('./components/NavBarTitle.vue')['default']
    NavDropdownLink: typeof import('./components/NavDropdownLink.vue')['default']
    NavDropdownLinkItem: typeof import('./components/NavDropdownLinkItem.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    NavLinks: typeof import('./components/NavLinks.vue')['default']
    NextAndPrevLinks: typeof import('./components/NextAndPrevLinks.vue')['default']
    OutboundLink: typeof import('./components/icons/OutboundLink.vue')['default']
    Page: typeof import('./components/Page.vue')['default']
    PageFooter: typeof import('./components/PageFooter.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    SideBarLinks: typeof import('./components/SideBarLinks.vue')['default']
    ToggleSideBarButton: typeof import('./components/ToggleSideBarButton.vue')['default']
  }
}

export { }
